---
- hosts: all
  become: yes

  vars:
    - var: ansible_python_interpreter=/usr/bin/python3

  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: System {{ var }}