---
- name: postgresql demo
  hosts: all
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name:
          - postgresql
          - postgresql-contrib
          - postgresql-libs
          - python3-psycopg2
        state: present

# ---
# - hosts: all
#   become: yes

#   vars:
#     - var: ansible_python_interpreter=/usr/bin/python3

#   tasks:
#     - debug:
#         msg: test{{var}}