---
- name: Install python in target node with ansible
  hosts: localhost
  become: true
  gather_facts: no
  pre_tasks:
  - name: install python
    raw: script.sh
    args:
      executable: /bin/bash
  tasks:
    - debug:
        msg: "This is a test"    